print('########################################')
print('#         ALGORITMOS EM PYTHON         #')
print('########################################')
print('#  Escolha a opção desejada            #')
print('# 1. Fibonacci                         #')
print('#                                      #')
print('########################################')